### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by OR13** [ConsiderItDone/transmute-industries-assignment#1]
When running:

`./start.sh`

I get:

```
geth ip is 172.59.0.2
Waiting for ethereum network and ethereum bridge...
OAR is No files found in /tmp/instance folder...
Unable to find image 'files:latest' locally
docker: Error response from daemon: repository files not found: does not exist or no pull access.
See 'docker run --help'.
Stopping oraclize-bridge ... done
Stopping oraclize-geth ... done
Going to remove oraclize-bridge, oraclize-geth
Removing oraclize-bridge ... done
Removing oraclize-geth ... done
```

Can you add some clarity on the extract process for running the truffle test?

`* extract Oraclize Address Resolver (OAR) from `ethereum-bridge` config`

^ this line could be elaborated on.

Seems like the compose services are working, why not add the truffle docker stuff to compose?

**Comment by ramilexe** [comment]
@OR13 I updated code. Added waiting script so you shouldn't see error message `No files found in /tmp/instance folder`

>Can you add some clarity on the extract process for running the truffle test?

Because we run test on private Ethereum network we need to define `Oraclize Address Resolver` address in contract (https://github.com/ConsiderItDone/transmute-industries-assignment/blob/master/truffle/contracts/YoutubeViews.sol#L12)
Ethereum-bridge returns this address after deploying contract. Also it stores it in json file: `/ethereum-bridge/config/instance/*.json`. I map host director `./files/instance` to this (https://github.com/ConsiderItDone/transmute-industries-assignment/blob/master/docker-compose.yml#L25). Wait for this file (https://github.com/ConsiderItDone/transmute-industries-assignment/blob/master/start.sh#L42) and then map this dir to docker container to extract OAR (https://github.com/ConsiderItDone/transmute-industries-assignment/blob/master/start.sh#L48) and run tests (https://github.com/ConsiderItDone/transmute-industries-assignment/blob/master/start.sh#L52)

Why not run in docker composer? 
Because if we will run this in CI we need main process to understand test passed or failed. If we run it in docker composer in background we will have to run something like that `docker logs -f ...` to know result

**Comment by OR13** [comment]
Excellent! Sorry for the long time to respond to this. This helps a lot.

**Comment by OR13** [comment]
@ramilexe Thanks for your feedback, I understand whats going on here, and this seems like it should all be working but the OAR dir seems to remain empty.

```
Waiting for ethereum network and ethereum bridge...
OAR dir is empty. Sleeping 10 s
OAR dir is empty. Sleeping 10 s
OAR dir is empty. Sleeping 10 s
...
```

Any idea how long this should take?

I forked and ran `./start`

Given that I have geth installed locally... perhapse there is some conflict? I can't see anything in compose that would suggest that.

Im wondering why i don't see any indication that `wait-for-geth.sh` is running...

**Comment by ramilexe** [comment]
>Any idea how long this should take?

On my laptop it takes about 5-6 minutes. How long did you wait?

Also, for debugging use `docker-compose logs -f`.
Could you  provide logs from Geth and Bridge containers?

>Given that I have geth installed locally... perhapse there is some conflict? I can't see anything in compose that would suggest that.

I think it is cause of problem. Because I use `docker inspect` to determine geth ip (https://github.com/ConsiderItDone/transmute-industries-assignment/blob/master/start.sh#L36)
